# Generated by Django 5.2.8 on 2025-11-24 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('danceability', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('mode', models.IntegerField(null=True)),
                ('acousticness', models.FloatField(null=True)),
                ('tempo', models.FloatField(null=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('num_sections', models.IntegerField(null=True)),
                ('num_segments', models.IntegerField(null=True)),
                ('star_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
