# Generated by Django 5.2.8 on 2025-11-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
    ]
