# Generated by Django 5.2.8 on 2025-11-24 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_playlist_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='star_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
